- hosts: localhost
  become: true
  tasks:
  - name: Install zsh
    apt: pkg=zsh
    sudo: yes

  - name: Install git
    apt: pkg=git
    sudo: yes

  - name: install curl
    apt: pkg=curl
    sudo: yes

  - name: Install visual Studio code
    become_user: root
    shell: |
     curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg     
     install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
     sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
     apt-get install apt-transport-https
     apt-get update
     apt-get install code


  - name: Install .asdf
    shell: |
     git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
     echo -e '. $HOME/.asdf/asdf.sh' >> ~/.zshrc

  - name: install docker
    become_user: root
    shell: |
     apt-get update
     apt-get install apt-transport-https ca-certificates gnupg-agent software-properties-common
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   
  - name: create base folder structure
    shell: |
     mkdir ~/Desktop/projects
     mkdir ~/Desktop/projects/studium
       
